using System.ComponentModel;
using System.Reflection;
using System.Text;
using System.Xml;
using System.Xml.Linq;
using MGUI.Core.UI.XAML;

return new XamlSchemaGenerator().Run(args);

internal sealed class XamlSchemaGenerator
{
    private static readonly XNamespace Xs = "http://www.w3.org/2001/XMLSchema";

    private readonly Assembly _assembly = typeof(XAMLParser).Assembly;
    private readonly IReadOnlyList<Type> _schemaTypes;
    private readonly IReadOnlyList<Type> _concreteSchemaTypes;

    public XamlSchemaGenerator()
    {
        _schemaTypes = _assembly
            .GetExportedTypes()
            .Where(IsSchemaModelType)
            .OrderBy(GetInheritanceDepth)
            .ThenBy(x => x.Name, StringComparer.Ordinal)
            .ToArray();
        _concreteSchemaTypes = _schemaTypes
            .Where(x => !x.IsAbstract)
            .OrderBy(x => x.Name, StringComparer.Ordinal)
            .ToArray();
    }

    public int Run(string[] args)
    {
        string outputPath = GetOutputPath(args);
        XDocument schema = GenerateSchemaDocument();

        string? outputDirectory = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrWhiteSpace(outputDirectory))
        {
            Directory.CreateDirectory(outputDirectory);
        }

        XmlWriterSettings settings = new()
        {
            Encoding = new UTF8Encoding(false),
            Indent = true,
            OmitXmlDeclaration = false,
            NewLineChars = Environment.NewLine,
            NewLineHandling = NewLineHandling.Replace,
        };

        using XmlWriter writer = XmlWriter.Create(outputPath, settings);
        schema.Save(writer);
        return 0;
    }

    private XDocument GenerateSchemaDocument()
    {
        XElement schema = new(
            Xs + "schema",
            new XAttribute("targetNamespace", XAMLParser.XMLLocalNameSpaceUri),
            new XAttribute(XNamespace.Xmlns + "xs", Xs.NamespaceName),
            new XAttribute(XNamespace.Xmlns + "mgui", XAMLParser.XMLLocalNameSpaceUri),
            new XAttribute("elementFormDefault", "qualified"),
            new XAttribute("attributeFormDefault", "unqualified")
        );

        schema.Add(
            new XComment(
                "Generated by tools/MGUI.XamlSchemaGenerator from the public MGUI.Core.UI.XAML source model."
            )
        );

        foreach (Type enumType in GetReferencedEnumTypes())
        {
            schema.Add(GenerateEnumType(enumType));
        }

        foreach (Type type in _schemaTypes)
        {
            schema.Add(GenerateComplexType(type));
        }

        foreach (Type type in _concreteSchemaTypes)
        {
            schema.Add(
                new XElement(
                    Xs + "element",
                    new XAttribute("name", type.Name),
                    new XAttribute("type", $"mgui:{GetSchemaTypeName(type)}")
                )
            );
        }

        return new XDocument(new XDeclaration("1.0", "utf-8", "yes"), schema);
    }

    private XElement GenerateEnumType(Type enumType)
    {
        XElement simpleType = new(
            Xs + "simpleType",
            new XAttribute("name", GetEnumSchemaTypeName(enumType))
        );

        XElement restriction = new(Xs + "restriction", new XAttribute("base", "xs:string"));
        foreach (string enumName in Enum.GetNames(enumType))
        {
            restriction.Add(new XElement(Xs + "enumeration", new XAttribute("value", enumName)));
        }

        simpleType.Add(restriction);
        return simpleType;
    }

    private XElement GenerateComplexType(Type type)
    {
        XElement complexType = new(Xs + "complexType", new XAttribute("name", GetSchemaTypeName(type)));
        if (HasSimpleContent(type))
        {
            complexType.Add(new XAttribute("mixed", "true"));
        }

        Type? baseType = GetSchemaBaseType(type);
        if (baseType != null)
        {
            XElement extension = new(
                Xs + "extension",
                new XAttribute("base", $"mgui:{GetSchemaTypeName(baseType)}")
            );
            AddTypeMembers(extension, type);
            complexType.Add(new XElement(Xs + "complexContent", extension));
        }
        else
        {
            AddTypeMembers(complexType, type);
        }

        return complexType;
    }

    private void AddTypeMembers(XElement parent, Type type)
    {
        List<XElement> contentEntries = new();

        foreach (string childElementName in GetDirectContentElementNames(type))
        {
            contentEntries.Add(
                new XElement(Xs + "element", new XAttribute("ref", $"mgui:{childElementName}"))
            );
        }

        foreach (PropertyInfo property in GetPropertyElementCandidates(type))
        {
            XElement? propertyElement = GeneratePropertyElement(type, property);
            if (propertyElement != null)
            {
                contentEntries.Add(propertyElement);
            }
        }

        if (contentEntries.Count > 0)
        {
            XElement choice = new(
                Xs + "choice",
                new XAttribute("minOccurs", "0"),
                new XAttribute("maxOccurs", "unbounded")
            );

            foreach (XElement entry in contentEntries)
            {
                choice.Add(entry);
            }

            choice.Add(
                new XElement(
                    Xs + "any",
                    new XAttribute("namespace", "##other"),
                    new XAttribute("processContents", "lax"),
                    new XAttribute("minOccurs", "0"),
                    new XAttribute("maxOccurs", "unbounded")
                )
            );

            parent.Add(choice);
        }

        foreach (PropertyInfo property in GetAttributePropertiesDeclaredOn(type))
        {
            parent.Add(
                new XElement(
                    Xs + "attribute",
                    new XAttribute("name", property.Name),
                    new XAttribute("type", GetAttributeSchemaType(property.PropertyType))
                )
            );
        }

        parent.Add(
            new XElement(
                Xs + "anyAttribute",
                new XAttribute("namespace", "##other"),
                new XAttribute("processContents", "lax")
            )
        );
    }

    private XElement? GeneratePropertyElement(Type ownerType, PropertyInfo property)
    {
        Type? collectionItemType = GetCollectionItemType(property.PropertyType);
        bool isCollection = collectionItemType != null;
        Type acceptedType = collectionItemType ?? NormalizePropertyType(property.PropertyType);

        if (!IsSchemaModelType(acceptedType))
        {
            return null;
        }

        string propertyElementName = $"{ownerType.Name}.{property.Name}";
        XElement propertyElement = new(Xs + "element", new XAttribute("name", propertyElementName));
        XElement complexType = new(Xs + "complexType");
        XElement choice = new(
            Xs + "choice",
            new XAttribute("minOccurs", "0"),
            new XAttribute("maxOccurs", isCollection ? "unbounded" : "1")
        );

        foreach (string elementName in GetAssignableConcreteElementNames(acceptedType))
        {
            choice.Add(new XElement(Xs + "element", new XAttribute("ref", $"mgui:{elementName}")));
        }

        choice.Add(
            new XElement(
                Xs + "any",
                new XAttribute("namespace", "##other"),
                new XAttribute("processContents", "lax"),
                new XAttribute("minOccurs", "0"),
                new XAttribute("maxOccurs", isCollection ? "unbounded" : "1")
            )
        );

        complexType.Add(choice);
        complexType.Add(
            new XElement(
                Xs + "anyAttribute",
                new XAttribute("namespace", "##other"),
                new XAttribute("processContents", "lax")
            )
        );

        propertyElement.Add(complexType);
        return propertyElement;
    }

    private IEnumerable<Type> GetReferencedEnumTypes()
    {
        SortedDictionary<string, Type> enumTypes = new(StringComparer.Ordinal);

        foreach (Type type in _schemaTypes)
        {
            foreach (PropertyInfo property in GetAttributePropertiesVisibleOn(type))
            {
                Type normalizedPropertyType = NormalizePropertyType(property.PropertyType);
                if (normalizedPropertyType.IsEnum)
                {
                    string enumKey = normalizedPropertyType.FullName ?? normalizedPropertyType.Name;
                    enumTypes.TryAdd(enumKey, normalizedPropertyType);
                }
            }
        }

        return enumTypes.Values;
    }

    private IEnumerable<PropertyInfo> GetAttributePropertiesDeclaredOn(Type type)
    {
        return type
            .GetProperties(BindingFlags.Instance | BindingFlags.Public | BindingFlags.DeclaredOnly)
            .Where(x => x.CanWrite)
            .Where(x => x.GetIndexParameters().Length == 0)
            .Where(IsBrowsable)
            .Where(x => IsSimpleAttributeType(x.PropertyType))
            .OrderBy(x => x.Name, StringComparer.Ordinal);
    }

    private IEnumerable<PropertyInfo> GetAttributePropertiesVisibleOn(Type type)
    {
        return type
            .GetProperties(BindingFlags.Instance | BindingFlags.Public)
            .Where(x => x.CanWrite)
            .Where(x => x.GetIndexParameters().Length == 0)
            .Where(IsBrowsable)
            .Where(x => IsSimpleAttributeType(x.PropertyType));
    }

    private IEnumerable<PropertyInfo> GetPropertyElementCandidates(Type type)
    {
        string? contentPropertyName = GetContentPropertyName(type);

        return type
            .GetProperties(BindingFlags.Instance | BindingFlags.Public)
            .Where(x => x.CanWrite)
            .Where(x => x.GetIndexParameters().Length == 0)
            .Where(x => IsBrowsable(x) || x.Name == contentPropertyName)
            .Where(x => HasSchemaElementRepresentation(x.PropertyType))
            .OrderBy(x => x.Name, StringComparer.Ordinal);
    }

    private IEnumerable<string> GetDirectContentElementNames(Type type)
    {
        string? contentPropertyName = GetContentPropertyName(type);
        if (string.IsNullOrWhiteSpace(contentPropertyName))
        {
            return Array.Empty<string>();
        }

        PropertyInfo? contentProperty = type.GetProperty(contentPropertyName, BindingFlags.Instance | BindingFlags.Public);
        if (contentProperty == null)
        {
            return Array.Empty<string>();
        }

        Type acceptedType = GetCollectionItemType(contentProperty.PropertyType)
            ?? NormalizePropertyType(contentProperty.PropertyType);
        if (!IsSchemaModelType(acceptedType))
        {
            return Array.Empty<string>();
        }

        return GetAssignableConcreteElementNames(acceptedType);
    }

    private IEnumerable<string> GetAssignableConcreteElementNames(Type acceptedType)
    {
        return _concreteSchemaTypes
            .Where(acceptedType.IsAssignableFrom)
            .Select(x => x.Name)
            .OrderBy(x => x, StringComparer.Ordinal);
    }

    private static bool HasSchemaElementRepresentation(Type propertyType)
    {
        Type normalizedPropertyType = NormalizePropertyType(propertyType);
        Type? collectionItemType = GetCollectionItemType(normalizedPropertyType);

        if (collectionItemType != null)
        {
            return IsSchemaModelType(collectionItemType);
        }

        return IsSchemaModelType(normalizedPropertyType);
    }

    private static bool IsSimpleAttributeType(Type propertyType)
    {
        Type normalizedPropertyType = NormalizePropertyType(propertyType);

        if (normalizedPropertyType == typeof(string))
        {
            return true;
        }

        if (normalizedPropertyType == typeof(bool)
            || normalizedPropertyType == typeof(byte)
            || normalizedPropertyType == typeof(sbyte)
            || normalizedPropertyType == typeof(short)
            || normalizedPropertyType == typeof(ushort)
            || normalizedPropertyType == typeof(int)
            || normalizedPropertyType == typeof(uint)
            || normalizedPropertyType == typeof(long)
            || normalizedPropertyType == typeof(ulong)
            || normalizedPropertyType == typeof(float)
            || normalizedPropertyType == typeof(double)
            || normalizedPropertyType == typeof(decimal))
        {
            return true;
        }

        if (normalizedPropertyType.IsEnum)
        {
            return true;
        }

        if (GetCollectionItemType(normalizedPropertyType) != null)
        {
            return false;
        }

        TypeConverter converter = TypeDescriptor.GetConverter(normalizedPropertyType);
        return converter.CanConvertFrom(typeof(string));
    }

    private static Type NormalizePropertyType(Type propertyType)
    {
        return Nullable.GetUnderlyingType(propertyType) ?? propertyType;
    }

    private static string GetAttributeSchemaType(Type propertyType)
    {
        Type normalizedPropertyType = NormalizePropertyType(propertyType);

        if (normalizedPropertyType.IsEnum)
        {
            return $"mgui:{GetEnumSchemaTypeName(normalizedPropertyType)}";
        }

        return normalizedPropertyType switch
        {
            _ when normalizedPropertyType == typeof(bool) => "xs:boolean",
            _ when normalizedPropertyType == typeof(byte) => "xs:unsignedByte",
            _ when normalizedPropertyType == typeof(sbyte) => "xs:byte",
            _ when normalizedPropertyType == typeof(short) => "xs:short",
            _ when normalizedPropertyType == typeof(ushort) => "xs:unsignedShort",
            _ when normalizedPropertyType == typeof(int) => "xs:int",
            _ when normalizedPropertyType == typeof(uint) => "xs:unsignedInt",
            _ when normalizedPropertyType == typeof(long) => "xs:long",
            _ when normalizedPropertyType == typeof(ulong) => "xs:unsignedLong",
            _ when normalizedPropertyType == typeof(float) => "xs:float",
            _ when normalizedPropertyType == typeof(double) => "xs:double",
            _ when normalizedPropertyType == typeof(decimal) => "xs:decimal",
            _ => "xs:string",
        };
    }

    private static bool HasSimpleContent(Type type)
    {
        string? contentPropertyName = GetContentPropertyName(type);
        if (string.IsNullOrWhiteSpace(contentPropertyName))
        {
            return false;
        }

        PropertyInfo? contentProperty = type.GetProperty(
            contentPropertyName,
            BindingFlags.Instance | BindingFlags.Public
        );
        if (contentProperty == null)
        {
            return false;
        }

        Type normalizedPropertyType = NormalizePropertyType(contentProperty.PropertyType);
        return !IsSchemaModelType(normalizedPropertyType)
            && GetCollectionItemType(normalizedPropertyType) == null
            && IsSimpleAttributeType(normalizedPropertyType);
    }

    private static string? GetContentPropertyName(Type type)
    {
        for (Type? current = type; current != null; current = current.BaseType)
        {
            CustomAttributeData? attribute = current
                .GetCustomAttributesData()
                .FirstOrDefault(x => x.AttributeType.Name == "ContentPropertyAttribute");

            if (attribute?.ConstructorArguments.Count > 0)
            {
                return attribute.ConstructorArguments[0].Value as string;
            }
        }

        return null;
    }

    private static Type? GetSchemaBaseType(Type type)
    {
        for (Type? current = type.BaseType; current != null; current = current.BaseType)
        {
            if (IsSchemaModelType(current))
            {
                return current;
            }
        }

        return null;
    }

    private static bool IsSchemaModelType(Type type)
    {
        return type.IsPublic
            && type.Namespace == typeof(XAMLParser).Namespace
            && type != typeof(XAMLParser)
            && !typeof(TypeConverter).IsAssignableFrom(type);
    }

    private static bool IsBrowsable(PropertyInfo property)
    {
        BrowsableAttribute? attribute = property.GetCustomAttribute<BrowsableAttribute>();
        return attribute?.Browsable != false;
    }

    private static Type? GetCollectionItemType(Type type)
    {
        if (type == typeof(string))
        {
            return null;
        }

        Type normalizedType = NormalizePropertyType(type);

        if (normalizedType.IsArray)
        {
            return normalizedType.GetElementType();
        }

        if (normalizedType
            .GetInterfaces()
            .Any(x => x.IsGenericType && x.GetGenericTypeDefinition() == typeof(IDictionary<,>)))
        {
            return null;
        }

        IEnumerable<Type> candidates = normalizedType.IsGenericType
            ? new[] { normalizedType }.Concat(normalizedType.GetInterfaces())
            : normalizedType.GetInterfaces();

        Type? enumerableType = candidates.FirstOrDefault(
            x => x.IsGenericType && x.GetGenericTypeDefinition() == typeof(IEnumerable<>)
        );

        return enumerableType?.GetGenericArguments()[0];
    }

    private static int GetInheritanceDepth(Type type)
    {
        int depth = 0;
        for (Type? current = type.BaseType; current != null; current = current.BaseType)
        {
            depth++;
        }

        return depth;
    }

    private static string GetSchemaTypeName(Type type) => type.Name;

    private static string GetEnumSchemaTypeName(Type enumType) => enumType.Name + "Enum";

    private static string GetOutputPath(IReadOnlyList<string> args)
    {
        string? explicitOutputPath = args.FirstOrDefault(x => !string.IsNullOrWhiteSpace(x));
        if (!string.IsNullOrWhiteSpace(explicitOutputPath))
        {
            return Path.GetFullPath(explicitOutputPath);
        }

        string repoRoot = FindRepositoryRoot();
        return Path.Combine(repoRoot, "schemas", "mgui.xsd");
    }

    private static string FindRepositoryRoot()
    {
        string current = AppContext.BaseDirectory;
        while (!string.IsNullOrWhiteSpace(current))
        {
            if (File.Exists(Path.Combine(current, "MGUI.sln")))
            {
                return current;
            }

            current = Path.GetDirectoryName(current) ?? string.Empty;
        }

        throw new InvalidOperationException("Could not locate the MGUI repository root.");
    }
}
